language: ruby
rvm:
- 2.2
#- 2.1
#- 2.0
- 1.9.3
env:
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=debian:7 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.5.1
sudo: false
services:
- docker
script:
- wget -O- bit.ly/ansibletest | sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: Clm+Q4aJcqBP4JBjj+mYlUg44K4lpZPoFiD/DiR0E2J9egOSaviksE4tfUeeVz2CoZ2EfRZrJxyxHlbWLlF/HOm2ytmvELYL0OfLduumtcFAa0ck93QW4FssQq7AZhNqEp+XmTcQG6T3Fg8lhPE0we9uITK3FjKEl/iPqh6wrHc0IfTqnV9791/qpkesxPKCmbv8qNGuiPw7PymY1J6uG0KFDfTK7TKWamqLRArnMT4HyZxQSpi6jdBk0AwSHoALi43fAESrTNwj7SiWhYkd9/mg3Xx7C2DMNv34f7r1FXK0EbzM31KsV7BIm/UAsQHxWlOxo+llMKRhFc2FqoYlxWrg3R2406ZK6i2wnTmvDhsWw3SfiYhxhnEJd4JRhjYY9gdo7mj8oZTlebKgux2cBwc6cHv1euXaSX/uiKobOUNHWLqQQc8tIyygl1UW2bib8eVH59qSU4MGa4Ev3GI8VD4MavdNgrnx85AcbTQxLDlGD2YwrD0QZAaRVh07xwNRsqt5q4Fu4xwteIrN8SFWuHMhQGw2DfMgP8Kxtvt7yPdITvHZTBdSM1yoDy7jg3ZMOjqojj/JfXUayZO9yGhDWKACto5gnoFWCzfvSa8s/PusEycgfA22sCt2d84glxNf+xNc5rtdxPuJNGfdpxzCcENAQbP+m4OaFSaNz6Fsybo=
  email:
    recipients:
      secure: eAHVZqs07t1gKibOE4LG7cg9ikZdd/hcTPd+GZoWa5JslM3nP4j/5E7qvHB9RdTmpQcHmCvCT34faYEQWizMFQ4U2McX9NbYJCXMDzF5YiYCVzLPmLFtIZau8lvWEpk7jaTcThBQn0mKGFro0YoP3og/EGVEzNAnbIhe8snWv74CrbIlXzR7oRzrlhWFLYCHdfxs7gmWMT/btFcEUxZ724WkVU6UKO6tvPlpjMrhK+FDEcpNTXE9laUlEhBhzqMX+l+2N3lCfzqTxANUHHLF3fXtUNeTSaBVSEuRRz4P6JTN03c78ksdkadKFRUzxOLVu+1of2az7dZdEv1G4ljCQ3864pxi8Ln4jg0KtA+w9rFNMO5RIQ9gDIU8QVkV8Oe4XnIx8o+pTgxhH1mF6qyKOxFMpl2v38oeewdFYKi0V+pRVtCc2KnYAUu69TbPnF1yIO9Vsl9X0vHAd0E1SYcm99QmCdX1jefuodGZfxSgjxUj2Rz+Clqi7bJ+BfLsVcEd/cUVBrZASCy9S6kPtueebNdLJ/upy/CdZHjTg9aDQ4tY9cknjj/P5Nhql5PafGAy+QuldVJlPM65UBAZPXlYTtn6m40AYgu//sdvNEd4YtF+F8dqlxtJSKr7MwvhwwxLjSj/cKPdGEzA5LsKo5mANXxurmBWH+uoqiFbQdOX5NQ=
